- name: Check if folder exists
  ansible.builtin.shell: "{{JENKINS_CLI_PREFIX}} get-job {{item.name}}"
  ignore_errors: true
  register: check_dir

- name: Update Job Template
  ansible.builtin.template:
    src: folders-job.xml
    dest: /tmp/job.xml

- name: Create a Folder
  when: check_dir.rc == 3
  ansible.builtin.shell: "cat /tmp/job.xml | {{JENKINS_CLI_PREFIX}} create-job {{item.name}}"

- name: Update a Folder
  when: check_dir.rc == 0
  ansible.builtin.shell: "cat /tmp/job.xml | {{JENKINS_CLI_PREFIX}} update-job {{item.name}}"